[phases.install]
cmds = [
  "composer install --ignore-platform-reqs",
  "npm install --legacy-peer-deps"
]

[start]
cmd = "mkdir -p /var/log/nginx && node /assets/scripts/prestart.mjs /assets/nginx.template.conf /nginx.conf && node /app/fix-nginx-conf.mjs /nginx.conf && (php-fpm -y /assets/php-fpm.conf & nginx -c /nginx.conf)"
